version: '3'

services:
  frontend:
    build:
      context: ../../frontend/Car-parking-react-frontend
    image: frontend-app
    networks:
      - frontend
    ports:
      - "7000:80"
  app_api:
    build:
      context: .
    image: car-park   
    ports:
      - "8080:8080" 
    networks: 
      - backend
      - frontend
    depends_on: 
      - postgres       
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demodb
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks: 
      - backend

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped
    networks: 
      - backend

volumes:
  postgres-data:

networks: 
  backend:
  frontend:
